# Generated by Django 4.2.13 on 2024-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sales_hall', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_takeaway', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_snappfood', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_company', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_special_company', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_charity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_misc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('salaries', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('raw_materials', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('consumables', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maintenance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('staff_meals', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('misc_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cost_to_sales_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'ordering': ['-date'],
            },
        ),
    ]
