# Generated by Django 4.2.13 on 2024-06-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
