# Generated by Django 5.0.6 on 2024-06-01 11:28

import django.utils.timezone
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('in', 'ورودی'), ('out', 'خروجی')], default='in', max_length=3)),
                ('quantities', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
