# Generated by Django 4.2.13 on 2024-06-14 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_monthlyreport_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsDebts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.JSONField(blank=True, default=dict, null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
