# Generated by Django 4.2.13 on 2024-06-14 07:57

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_claimsdebts'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsdebts',
            name='claimsdebts_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='', unique=True),
        ),
    ]
