# Generated by Django 4.2.13 on 2024-06-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_claimsdebts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsdebts',
            name='type',
            field=models.CharField(choices=[('claim', 'طلب'), ('debt', 'بدهی')], max_length=10),
        ),
    ]
