# Generated by Django 4.2.13 on 2024-06-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_alter_claimsdebts_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='sales',
            new_name='sales_charity1',
        ),
    ]
