# Generated by Django 4.2.13 on 2024-06-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_rename_sales_monthlyreport_sales_charity1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='overtime',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='staff_meals',
            new_name='hall',
        ),
    ]
