# Generated by Django 4.2.13 on 2024-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_rename_overtime_monthlyreport_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='misc_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='monthly_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
