# Generated by Django 4.2.13 on 2024-08-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_claimdebt_delete_claimsdebts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdebt',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claimdebt',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='claimdebt',
            name='level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claimdebt',
            name='staff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claimdebt',
            name='totalـclaims',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claimdebt',
            name='totalـdebts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claimdebt',
            name='value_added_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
