# Generated by Django 4.2.13 on 2024-08-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_alter_claimdebt_balance_alter_claimdebt_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimdebt',
            old_name='totalـclaims',
            new_name='total_claims',
        ),
        migrations.RenameField(
            model_name='claimdebt',
            old_name='totalـdebts',
            new_name='total_debts',
        ),
    ]
