# Generated by Django 5.0.6 on 2024-06-05 17:58

import django.utils.timezone
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='', unique=True)),
                ('name', models.CharField(max_length=300)),
                ('ingredients', models.JSONField(blank=True, default=dict)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
