# Generated by Django 5.0.6 on 2024-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_prices', models.JSONField()),
            ],
        ),
    ]
