# Generated by Django 4.2.13 on 2024-06-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipeprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSaleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_prices', models.JSONField()),
            ],
        ),
    ]
