# Generated by Django 4.2.13 on 2024-06-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipesalefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesalefile',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
