# Generated by Django 4.2.13 on 2024-06-13 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipesalefile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesalefile',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
