# Generated by Django 5.0.6 on 2024-05-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstuff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foodStuffCategory',
            new_name='Category',
        ),
    ]
