# Generated by Django 5.0.6 on 2024-05-30 15:40

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstuff', '0002_rename_foodstuffcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='', unique=True)),
                ('stuff_name', models.CharField(max_length=300)),
                ('stuff_scale', models.CharField(choices=[('Number', '(عدد)تعداد'), ('Weight', 'وزن(کیلوگرم)')], default='Weight', max_length=20)),
                ('stuff_category', models.ManyToManyField(related_name='stuff_category', to='foodstuff.category')),
            ],
        ),
    ]
