# Generated by Django 5.0.6 on 2024-05-31 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstuff', '0003_stuffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuffs',
            name='stuff_category',
        ),
        migrations.AlterField(
            model_name='stuffs',
            name='stuff_scale',
            field=models.CharField(choices=[('Weight', 'وزن(کیلوگرم)'), ('Number', '(عدد)تعداد')], default='Weight', max_length=20),
        ),
        migrations.AddField(
            model_name='stuffs',
            name='stuff_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stuffs', to='foodstuff.category'),
            preserve_default=False,
        ),
    ]
