# Generated by Django 5.0.6 on 2024-06-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstuff', '0005_price_alter_stuffs_stuff_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
