# Generated by Django 5.0.6 on 2024-06-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstuff', '0008_remove_price_price_id_alter_price_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='prices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
