# Generated by Django 5.0.6 on 2024-06-01 15:16

import django.utils.timezone
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstuff', '0010_alter_price_date_alter_price_id_alter_price_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='prices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
